const ALERT = "ALERT";
const USER_CONNECTED = "USER_CONNECTED";
const SEND_MESSAGE =   "SEND_MESSAGE";

const NEW_MESSAGE = "NEW_MESSAGE";
const FRIEND_REQUEST = "FRIEND_REQUEST";

const USER_TYPING = "USER_TYPING";
const USER_STOP_TYPING = "USER_STOP_TYPING";

export {
    USER_CONNECTED,
    SEND_MESSAGE,
    NEW_MESSAGE,
    FRIEND_REQUEST,
    ALERT,
    USER_TYPING,
    USER_STOP_TYPING
}